---

- name: oraclelinux9
  box: generic/oracle9
- name: debian10
  box: generic/debian10
- name: debian11
  box: generic/debian11
- name: ubuntu2004
  box: generic/ubuntu2004
- name: ubuntu2204
  box: generic/ubuntu2204
- name: fedora36
  box: generic/fedora36
- name: fedora37
  box: generic/fedora37
