---

- name: debian10
  box: generic/debian10
- name: debian11
  box: generic/debian11
- name: ubuntu2004
  box: generic/ubuntu2004
- name: ubuntu2204
  box: generic/ubuntu2204
- name: fedora35
  box: generic/fedora35
- name: fedora36
  box: generic/fedora36
